name: FirstPlugin
main: me.Streampy.firstplugin.Main
version: 1.0
commands:
  hallo:
    description: Hallo Speler
  fly:
    description: Laat jezelf vliegen!
  msg:
    description: stuur prive bericht
  broadcast:
    description: broadcast
  bc:
    description: broadcast gekort
  tpa:
    description: teleport naar andere speler
  tpaccept:
    description: accepteer teleport
  tpdeny:
    description: deny een teleport
  tptoggle:
    description: zet tp naar jouw uit
  jail:
    description: jail een speler
  setspawn:
    description: set spawn point
  spawn: 
    description: ga naar spawn
  sethome:
    description: maak voor jezelf een home
  home:
    description: ga naar je home
  rename:
    description: verander de naam van het item
  info:
    description: krijg informatie over de speler
  setprefix:
    description: set een prefix van een speler
  setsuffix:
    description: set een suffix van een speler
  sc:
    description: set je scoreboard aan of uit
  gm:
    description: snel koppeling van gamemode veranderen